/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_RsaJni */

#ifndef _Included_jni_RsaJni
#define _Included_jni_RsaJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_RsaJni
 * Method:    encryptRsaByPublicKey
 * Signature: ([BLjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_jni_RsaJni_encryptRsaByPublicKey
  (JNIEnv *, jobject, jbyteArray, jstring);

/*
 * Class:     jni_RsaJni
 * Method:    decryptRsaByPrivateKey
 * Signature: ([BLjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_jni_RsaJni_decryptRsaByPrivateKey
  (JNIEnv *, jobject, jbyteArray, jstring);

/*
 * Class:     jni_RsaJni
 * Method:    encryptRsaByPrivateKey
 * Signature: ([BLjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_jni_RsaJni_encryptRsaByPrivateKey
  (JNIEnv *, jobject, jbyteArray, jstring);

/*
 * Class:     jni_RsaJni
 * Method:    decryptRsaByPublicKey
 * Signature: ([BLjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_jni_RsaJni_decryptRsaByPublicKey
  (JNIEnv *, jobject, jbyteArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
